### PR TITLE
contributors: merge the known contributor aliases

### PR DESCRIPTION
**Pull request by AlexIljin**
What do you think about this?
Without this change the `contributors` vocab is kind of generic and can be used on any git repository, and with this change it's much more specific to the Factor repo. I'm not sure it the change is in line with the original intention behind the vocab.
On the other hand, if it's used on an unrelated repository, there is very little chance that the antialiasing will make any difference at all. It'll essentially be a no-op on almost any other repo in the world.

### CODE REVIEW

**Comment by mrjbq7** [comment]
Not sure! I can see it's usefulness for our repo though.

Btw, instead of ``extract-keys``, you should maybe use ``delete-at*`` or ``?delete-at``.  I'm not quite sure why we need both of those, but one of them should serve your purpose.

Using something like (untested):

```factor
unclip '[ over delete-at* [ _ pick at+ ] with when ] each
```

**Comment by AlexIljin** [comment]
I most certainly **would** use one of those, if they were a bit more discoverable. Reading through the docs I didn't see those words exist, because the help topic lists `delete-at`, and there are no pointers to the other variants!

**Comment by mrjbq7** [comment]
Yeah, I didn’t realize they existed either although I thought they *should* exist. Not sure why both variants are necessary.

**Comment by AlexIljin** [comment]
I see the only difference seems to be in using `at*` vs. `?at`, the latter outputs the key if it was not found in the assoc.

**Comment by AlexIljin** [comment]
Tested and pushed the newer version.

**Comment by AlexIljin** [comment]
It seems that in the code you suggested there is a weird interaction between `fry` and `with`.

**Comment by AlexIljin** [comment]
See issue #2328 about the weird interaction.

**Comment by AlexIljin** [comment]
I have nothing to add to this PR.

**Comment by mrjbq7** [comment]
Thanks!

**Pull request merged**
