### PR TITLE
Trees

### PR DESCRIPTION
**Pull request by jonenst**
#1754 
I fixed some bugs in the extra:trees and added the features I was talking about.
I didn't go full meta-programming so the code is verbose, please improve if you can !
Also, I wasn't totally happy with the naming of the words, if anyone has better suggestions, please tell.

### CODE REVIEW

**Comment by jonenst** [comment]
Hmm wait I just realized that pop and slurp won't maintain the properties of subclasses of tree, that's not good. Let me rework that tomorow.

**Comment by jonenst** [comment]
Okay, now it's correct for all trees. I also changed >tree >avl and >splay in the case the input is a tree to attempt to keep the shape by choosing the order of the alist derived from the input (bfs for regular tree and avl, reverse bfs for splay tree).

I was thinking of adding a tree.traversal vocabulary with visitors for inorder, preorder, postorder and bfs traversals, along with >alist equivalents (and move the code that I added for bfs in trees.factor), what do you think ?

**Comment by mrjbq7** [comment]
Awesome! It sounds maybe useful to put in a traversal vocabulary. Maybe a stylistic thing, but if you are leaning toward it, sure.

**Comment by jonenst** [comment]
> It sounds maybe useful to put in a traversal vocabulary. Maybe a stylistic thing, but if you are leaning toward it, sure.

I didn't understand... What's the stylistic alternative ?

Anyway, if you have time to review the code in this PR that'd be great. Especially come up with better names :)

**Comment by mrjbq7** [comment]
> I was thinking of adding a tree.traversal vocabulary with visitors for inorder, preorder, postorder and bfs traversals, along with >alist equivalents (and move the code that I added for bfs in trees.factor), what do you think ?

I was just thinking that whether you have a massive ``trees`` vocab or split out to ``trees.traversal`` is a stylistic judgment.  I do like the idea of the ``trees.traversal`` (similar to ``xml.traversal``) because the API seems to be growing and it could be a little confusing looking at all the words in ``trees``?

**Comment by mrjbq7** [comment]
By the way, I merged this.  Thanks!!

New features, bug fixes - love it!

**Pull request closed without merging**
