### PR TITLE
typo fixed in wipe-docs.factor

### PR DESCRIPTION
**Pull request by shruti-sen2004**
ation -> action

Corrected the typo in wipes-docs.factor

### CODE REVIEW

**Comment by shruti-sen2004** [comment]
@mrjbq7 @razetime @gifti258 Please merge my pull request.

**Comment by razetime** [comment]
Please do not ping contributors on every PR. Please put in the effort to make a useful contribution. Creating PRs for many single typos is a waste of time for contributors and maintainers.

**Comment by shruti-sen2004** [comment]
@razetime thank you for letting me know. I would try to contribute something else. But I would like to say that these kind of prs were merged in this repo before and were not marked as spams so I thought I could contribute too ....thanks for letting me know that I was wrong.  If you would check the last 3-4 prs that were merged they almost did the same things but were merged successfull without any spam report.

**Comment by mrjbq7** [comment]
We appreciate contributions, but it is not necessary to ping us or to push for merging when these are not critical changes.

If you are doing a series of these, perhaps batch them up.

Thanks,

**Comment by shruti-sen2004** [comment]
Hello maintainers, I would be grateful if you would remove the hacktoberfest spam label from these pr ....as these contributions were not intended to be under my hacktoberfest contributions...the spam label has affected my contributions that had been made way before...although I have completed my hacktoberfest earlier this month.....hacktober fest has now disqualified me...it is a formal request....let the hacktoberfest invalid tag be there...but please remove the spam tag. I assure you these kind of contributions will not be further continued from my side. 
Thank you.

**Comment by shruti-sen2004** [comment]
@mrjbq7 sorry ..I did not mean to disturb...it's quite important that's why I am tagging you.

**Comment by mrjbq7** [comment]
Hi @shruti-sen2004, if these were done with good intentions, then I appreciate the contributions.  Typically, we don't see a lot of separate PRs like this, but I have gone and removed the spam label from the typo fix PRs.  In the future, I would hope to encourage more extensive contributions if you have future interest in participating in this community. I think the wave of small grammatical and unnecessary re-write PRs caused the community to begin rejecting this to prevent future spam.

**Pull request merged**
