### PR TITLE
io.launcher.windows: hide window of the launched process

### PR DESCRIPTION
**Pull request by AlexIljin**
As a result of this patch, all the child processes start completely hidden from view: their main windows are not displayed on screen, and they are not shown on the taskbar. This is to avoid flashing of the console windows when a program in Factor calls external utilities.

What do you think? Is there a better way to include this feature? Maybe make it optional?

### CODE REVIEW

**Comment by bjourne** [comment]
Isn't that dependent on if you start Factor using factor.com or factor.exe?

**Comment by erg** [comment]
I think it should be an option on ``process`` in "io.launcher".

**Comment by AlexIljin** [comment]
@bjourne: "Isn't that dependent on if you start Factor using factor.com or factor.exe?"

Yes, it is. If you run factor.com, all the child console processes will reuse its window, and there will be no flashing. But if you run factor.exe explicitly because you don't want to see the console window(s), all the child processes will create their console windows anyway, and not even in the background - they will flash in your face.

@erg: "I think it should be an option on process in "io.launcher"."

Could you suggest a name for the slot? `hidden`?

**Comment by AlexIljin** [comment]
OK, I've updated the proposal. Now there is the `hidden` slot. Added documentation.

What I actually needed was that processes spawned by `<process-stream>` were hidden, hence the second patch. What do you say?

**Comment by bjourne** [comment]
Looks good to me. A unit test or two testing the feature would be nice though.

**Comment by AlexIljin** [comment]
@bjourne: "A unit test or two testing the feature would be nice though."

I don't know how to test for the absence of a window. Or did you have something else in mind?

**Comment by erg** [comment]
You could just make sure it still launches with either option and let someone complain is the window shows.

**Comment by bjourne** [comment]
Yep. Didn't mean something fancy. If I understand your pr, you could add something simple like:

    { t } [
        "dir" utf8 (process-stream) hidden>> swap stream-contents drop
    ] unit-test

to `io.launcher.tests`.

**Comment by AlexIljin** [comment]
@erg, @bjourne: OK, I'll do it sometime soon.

**Comment by AlexIljin** [comment]
OK, done.

**Comment by mrjbq7** [comment]
Question: should we default ``hidden`` to true or false?  The new (default) behavior is different than the old (default) behavior.

**Comment by bjourne** [comment]
Probably best to keep it off by default. Otherwise when you run a windowed program like notepad.exe, the window won't show up.

**Comment by AlexIljin** [comment]
@mrjbq7: the new default behavior is only changed for processes started using `(process-stream)`, i.e. by `<process-stream>` and `with-process-stream*`. Only in `(process-stream)` is `hidden` set to `t`, otherwise it defaults to `f` and to the old behavior.

The presumption is that you only do `process-stream` for console processes that work with STDIO streams. That's generally not the case with GUI apps, such as Notepad.

**Comment by mrjbq7** [comment]
That sounds reasonable, I think.  @bjourne?

Merged, thanks!!

**Comment by bjourne** [comment]
Yeah, seems right. It probably should be mentioned in the docs also.

**Comment by AlexIljin** [comment]
@bjourne: added the mention in PR #1714.

@mrjbq7: thanks for merging! Close this PR?

**Pull request closed without merging**
