### PR TITLE
Use https rather than git protocol in download instructions

### PR DESCRIPTION
**Pull request by khinsen**
Only project members can clone via the git protocol.

### CODE REVIEW

**Comment by erg** [comment]
I believe it's anyone with a github ssh key, not just project members.

**Comment by khinsen** [comment]
I have a GitHub SSH key, but it works only for repositories I have write access on. I suppose the git protocol can't provide read-only access, but that's just my hypothesis.

Anyway, I discovered this issue by trying to follow the instructions and failing!

**Comment by bpollack** [comment]
This issue is conflating two different things:
 1. Anyone can clone anything over SSH. I just quickly verified that by cloning github.com/opencv/opencv over SSH (and you can trivially verify I not only am not a core contributor, but have never even contributed a patch).
 2. That said, `git:` is not the SSH protocol; it's the old unencrypted cloning protocol. That got disabled a couple years ago (see https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git). It won't work on _any_ repository, so it was a good catch to fix the docs.
Thanks for the patch, @khinsen! It's the right fix for the `README.md`. But definitely feel free to work with an SSH clone if you prefer.

**Comment by khinsen** [comment]
Thanks @bpollack, I learned something about git today!

**Pull request merged**
