### PR TITLE
Updated arrays.factor

### PR DESCRIPTION
**Pull request by DivyaSharma59**

### CODE REVIEW

**Comment by AlexIljin** [comment]
I think the commit message should be like this:
`arrays: remove an extra empty line`

**Comment by bpollack** [comment]
This is a bot; he’s just doing PRs where he deletes blank lines.

**Comment by mrjbq7** [comment]
A bot that deletes lines in the middle of a file? That’s whacky.

**Comment by bpollack** [comment]
Might be a person who wants to be able to say they've contributed to a bunch of stuff, but that's literally all they do. If you go look at their profile, they've fired off several PRs for things like Hugo that all look like this.

**Pull request closed without merging**
