### PR TITLE
elevate.py port to basis/elevate

### PR DESCRIPTION
**Pull request by catb0t**
this is a near-exact port of https://github.com/barneygale/elevate | #1994 

1. should this go in `extra` or `basis`? 
2. i'm looking for help to finish and test the Windows and Mac OSX implementations. I have access to a Windows machine, but not a Mac or Applescript.

3. specifically: i don't know how to use `with-out-parameters` properly (to avoid `local-allocation-error`) with `GetProcessToken` etc to implement `windows already-root?`

4. the documentation is almost done, but not quite there yet, as there are a bunch of unfixable-bugs (in e.g `gksudo` messaging) and limitations that need to be mentioned somewhere.

5. (when this is merged, `apple-script-quote` should probably be moved into `cocoa.apple-script`)

### CODE REVIEW

**Comment by catb0t** [comment]
@erg any ideas about this? :D

**Comment by erg** [comment]
Hey @catb0t, this is great! I'll merge it this weekend, with or without windows support. I think it can go in basis/ because it has docs. Can you move the apple-script now? ``with-out-parameters`` is kind of tricky...I'll look this weekend.

**Comment by mrjbq7** [comment]
Very cool.  Does this have good cross-platform tests?

**Comment by catb0t** [comment]
I thought about writing tests but the main problem is that the tests for `elevated` and `elevate` would require a password input or to be run by `root` anyway, which is not great.

aside from that: 

* to test `elevated` the unit-test must somehow know robustly whether the launched process had elevated privileges or not, 

* to test `elevate ( -- )`, which *may* relaunch (replace with `execv`) the current Factor process (Unix) or *will* kill and relaunch the current Factor process (Windows), it is like trying to test `exit` or `execv` anyway -- it's impossible because the testing process will be destroyed.

i guess to test `elevate` it could be possible to launch a completely new independent Factor VM and tell *it* to `elevate`?

**Comment by catb0t** [comment]
@erg Ok, I moved `quote-apple-script`, but I haven't got a Mac to test it, so if you want to make sure it actually runs you should pull my branch.

**Comment by catb0t** [comment]
hmm, these line ending changes in those XML files have really f**ed up my branch! i can't do anything about this except commit the changes, i can't even `revert` or `rebase` the commit without an error.

**Comment by catb0t** [comment]
```
$ git checkout master
error: Your local changes to the following files would be overwritten by checkout:
	basis/xml/tests/xmltest/canonxml.html
	basis/xml/tests/xmltest/readme.html
	extra/webapps/fjsc/www/termlib/faq.html
	extra/webapps/fjsc/www/termlib/index.html
	extra/webapps/fjsc/www/termlib/multiterm_test.html
	extra/webapps/fjsc/www/termlib/parser_sample.html
Please commit your changes or stash them before you switch branches.
Aborting

$ git add --all; git stash
warning: CRLF will be replaced by LF in basis/xml/tests/xmltest/canonxml.html.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in basis/xml/tests/xmltest/readme.html.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in extra/webapps/fjsc/www/termlib/faq.html.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in extra/webapps/fjsc/www/termlib/index.html.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in extra/webapps/fjsc/www/termlib/multiterm_test.html.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in extra/webapps/fjsc/www/termlib/parser_sample.html.
The file will have its original line endings in your working directory.
Saved working directory and index state WIP on sudo-port: 953b92c80a Revert "throw away this commit"

$ git checkout master
error: Your local changes to the following files would be overwritten by checkout:
	basis/xml/tests/xmltest/canonxml.html
	basis/xml/tests/xmltest/readme.html
	extra/webapps/fjsc/www/termlib/faq.html
	extra/webapps/fjsc/www/termlib/index.html
	extra/webapps/fjsc/www/termlib/multiterm_test.html
	extra/webapps/fjsc/www/termlib/parser_sample.html
Please commit your changes or stash them before you switch branches.
Aborting
```

**Comment by AlexIljin** [comment]
How about `git reset --hard` or [this](https://stackoverflow.com/questions/17223527/how-do-i-force-git-to-checkout-the-master-branch-and-remove-carriage-returns-aft)?

**Comment by catb0t** [comment]
ok, i think i'll re-open this pull request with @erg and my new changes and from a branch that isn't messed up

**Pull request closed without merging**
