### PR TITLE
Win transparent text background

### PR DESCRIPTION
**Pull request by AlexIljin**
This fixes issues #152 and #1658.

### CODE REVIEW

**Comment by erg** [comment]
Merged!!

**Comment by nicolas-p** [comment]
I've been waiting for a solution to this bug for three years. Big thanks!

**Comment by AlexIljin** [comment]
> I've been waiting for a solution to this bug for three years. Big thanks!

@nicolas-p, does it mean there will finally be a new `skov` release?

**Comment by nicolas-p** [comment]
Well, I'm quite busy right now, so maybe later this year. I'm happy to see that there's at least one person who's expecting it! It will look good on Windows for the first time.

**Pull request closed without merging**
