### PR TITLE
#2204 : use std handles if associated with streams

### PR DESCRIPTION
**Pull request by nomennescio**
#2204

### CODE REVIEW

**Comment by mrjbq7** [comment]
Does -2 have a constant name somewhere defined?

**Comment by mrjbq7** [comment]
Should we open ``nul`` only once using ``r+`` and share the handle or is that not necessary? since they can be closed independently by factor?

**Comment by mrjbq7** [comment]
shouldn't we ``fopen("nul", "r+")`` or at least ``w`` for the stdout and stderr handles?

**Comment by nomennescio** [comment]
> Should we open `nul` only once using `r+` and share the handle or is that not necessary? since they can be closed independently by factor?

I think it's indeed better to have 3 independent handles

**Comment by nomennescio** [comment]
> Does -2 have a constant name somewhere defined?

I can introduce a constant, but I didn't see anything mentioned in the documentation

**Comment by erg** [comment]
There's no named constant for this. i asked chatgpt so it's true.

we could do this if we wanted though:

```
#define INVALID_HANDLE_FD -2
#define VALID_HANDLE(handle, mode) (_fileno(handle) == INVALID_HANDLE_FD ? fopen("nul", mode) : handle)
```

**Pull request merged**
