### PR TITLE
fixup! [misc] vim/syntax: Fixups

### PR DESCRIPTION
**Pull request by bb010g**
i'm bad at titling pull requests edition

---
This change is [Reviewable](https://reviewable.io/reviews/factor/factor/2301)

### CODE REVIEW

**Comment by mrjbq7** [comment]
I'm bad at rebasing edition!

Thanks!

**Comment by mrjbq7** [comment]
I still have weird ``NAN:`` highlighting.

You can look at the ``misc/syntax-test.factor`` and see that the ``NAN:`` highlighting screws up the ``STRUCT:`` highlighting and this diff fixes it (removing the ``@`` sign from the ``factorHexNoRadixTrans`` reference, but I don't think is correct way to fix it:

```diff
diff --git a/misc/vim/syntax/factor.vim b/misc/vim/syntax/factor.vim
index 0b325f83ec..09d84983fa 100644
--- a/misc/vim/syntax/factor.vim
+++ b/misc/vim/syntax/factor.vim
@@ -192,8 +192,7 @@ if !exists('g:factor_syn_no_error')
   syn match   factorOctError             /\v<[+-]=0o%(,\S*|\S*,|[0-7,]*[^0-7, ]\S*)>/
   syn cluster factorOct                 add=factorOctError
 endif
-syn match   factorOct                   /\v<[+-]=0o[0-7,]+>/
-syn region  factorNan matchgroup=factorNan start=/\v<NAN:>/ matchgroup=NONE end=/\v<\S+>/ contains=@factorComment,@factorHexNoRadixTrans
+syn region  factorNan matchgroup=factorNan start=/\v<NAN:>/ matchgroup=NONE end=/\v<\S+>/ contains=@factorComment,factorHexNoRadixTrans
 
 syn region  factorBackslash       start=/\v<\\>/   skip=/\v<!>/ end=/\v<\S+>/   contains=@factorComment
 syn region  factorMBackslash      start=/\v<M\\>/  skip=/\v<!>/ end=/\v<\S+%(\_\s+%(!>.*)?)+\S+>/   contains=@factorComment
```

**Comment by mrjbq7** [comment]
Also, now these don't highlight as numbers but should:

```
.1
-.1
```

**Comment by bb010g** [comment]
Okay, just got a bunch of improvements done (and my understanding of Vim's syntax system is more complete now). They're at present at bb010g/factor@3febae4b9c0eec0e6d4d9cdb04a44870223d290a, but I'll be bringing them up to your changes on master and PRing them when ready.

Thanks a bunch for the `syntax-test.factor` file.

**Comment by mrjbq7** [comment]
Cool!!!

**Comment by mrjbq7** [comment]
P.S., I use Vim all the time and super appreciate this!

**Comment by bb010g** [comment]
You're welcome! It's been interesting to see how the syntax highlighting sausage is made.

https://github.com/neovim/neovim/issues/11724 is awesome and can't happen soon enough.

**Pull request merged**
