### PR TITLE
Sodium

### PR DESCRIPTION
**Pull request by AlexIljin**
Hey'all!

  I have finished the Libsodium API and added a small unit-test that demonstrates the public-key authenticated encryption. There is next to no error handling in the vocab at the moment, suggestions are welcome.

### CODE REVIEW

**Comment by erg** [comment]
Cool! Could you add a test or two that call into the library please?

**Comment by AlexIljin** [comment]
"sodium: the add essential crypto-box-* words and a unit-test"?

**Comment by AlexIljin** [comment]
Damn, sorry! The unit-test in not in the commit : ))
Wait a second.

**Comment by AlexIljin** [comment]
OK, ready.

**Comment by erg** [comment]
I forgot, I can't actually use the github buttons 🥇

**Comment by AlexIljin** [comment]
I *thought* this looked weird.
Anyway, I've just proposed a change to the [libsodium-doc](https://github.com/jedisct1/libsodium-doc/) project to add Factor to the list of languages supporting libsodium in their standard libraries.

**Comment by AlexIljin** [comment]
Yay! They merged the patch.
Spreading the word...

**Pull request merged**
