### PR TITLE
io.pathnames: fix separator when appending paths in Windows

### PR DESCRIPTION
**Pull request by masweeney**
This fixes issue #1701.

### CODE REVIEW

**Comment by mrjbq7** [comment]
Merged, thanks!!

**Comment by mrjbq7** [comment]
Reverted, this breaks test cases.

**Comment by masweeney** [comment]
Right now I am modifying the tests to call `normalize-path` on both paths and check for equality. This is pretty inelegant, so let me know if you have a better idea for getting the tests to work more consistently across platforms.

**Comment by mrjbq7** [comment]
I'd have to look at it. Elegant is better than inelegant. Having normalize path equality doesn't check the intermediate result.

**Comment by masweeney** [comment]
Unfortunately, test cases like `"/usr" "lib" append-path` don't make much sense on windows anyway. The updated version returns `/usr\\lib`, which I suppose is correct given the input, but not very meaningful. To check the intermediate, each test could branch on OS and check for equality separately, which might be the best option.

**Comment by mrjbq7** [comment]
I could be find to have something like:

```factor
os windows? [
    { "C:\\foo" } [ "C:" "foo" append-path ] unit-test
] [
    { "/usr/foo" } [ "/usr" "foo" append-path ] unit-test
] if
```

**Comment by bjourne** [comment]
I say good work! You can also use the literal syntax:
```factor
${ "/usr" "foo" path-separator glue } [ "/usr" "foo" append-path ]  unit-test
``` 
Also updating the tests and documentation is really important.

**Comment by masweeney** [comment]
I've updated the tests, so hopefully everything works now.

I was not able to run this test on windows because it's an older version, but everything else worked.
```
[| path |
    { } [ 2 [ path touch-file ] times ] unit-test
] with-test-file
```

**Comment by bpollack** [comment]
Okay @masweeney, sorry for the lag; tests all look good both on Windows and Linux, so I'm going to go ahead and merge this if you're okay with that. I am going to collapse your two commits into just one, though, since it seems to me that your second commit is strictly cleaning up behavior that should've been in the first patch.

**Comment by mrjbq7** [comment]
Do we care what happens with mixed separators?  (Meaning the paths have mixed separators and stuff still works).

Currently:

```factor
IN: scratchpad "C:\\Users" "John" append-path .
"C:\\Users/John"
```

Proposed (note, I changed the arguments a little bit):

```factor
IN: scratchpad "C:/Users" "John" append-path .
"C:/Users\\John"
```

**Comment by AlexIljin** [comment]
@mrjbq7: I think the mixed separators are not an issue of this PR. We had them before, and we have them still. This PR is a step in the right direction, so I like it.

When I want my paths fully compliant, I use `normalize-path`, which switches all instances of `/` to `\` on Windows. After that the proposed `append-path` won't break introduce new `/`s, so that's good. That's my view on the matter.

**Comment by bpollack** [comment]
This landed in 35f82c90f3b22457b42143143bc08d5298462ca6; I'm going to close it.

**Pull request closed without merging**
