### PR TITLE
Add documentation for sift!

### PR DESCRIPTION
**Pull request by chunes3**
Hello! Long-time Factor user and first-time pull requester here. I am very interested in adding documentation to Factor but I figured I'd start small to make sure I'm doing this correctly. This is documentation for the `sift!` word. Please scrutinize extra carefully to make sure I'm not messing anything up.

Old docs: 
old-sift

New docs:
new-sift

### CODE REVIEW

**Comment by alex-ilin** [comment]
Looks pretty good!
After your change, what does the "See also" section of the word `filter!` look like?

**Comment by alex-ilin** [comment]
Maybe it would be a good idea to copy the "Notes" section from the `filter!` word.

**Comment by chunes3** [comment]
Good idea on adding the notes section. Added.

As for the rest, are you saying it would be a good idea to add `sift!` to the `See also` of `filter!` (and maybe `sift`)?

**Comment by alex-ilin** [comment]
I'm saying that due to the way `$see-also` works, your version might have replaced the original one, which was "filter, filter-as, reject, reject-as, reject!, sift, harvest". That would mean that the list got shorter.

**Comment by chunes3** [comment]
`filter!` still has its original `$see-also` after the changes.

**Comment by alex-ilin** [comment]
I see you are correct, I mixed `$see-also` with `related-words`.

**Comment by mrjbq7** [comment]
Awesome, thanks!

**Pull request merged**
