### PR TITLE
sequences: Add 2any? combinator

### PR DESCRIPTION
**Pull request by timor**
Missing member of the pairwise sequence combinator family.

### CODE REVIEW

**Comment by timor** [comment]
CI fails on linting docs.  Is this because it is a change to a core vocab?

**Comment by mrjbq7** [comment]
It appears that our Travis CI just builds from the existing boot image, so changes to core aren't incorporated until the boot image is updated.  That's less than helpful!

**Comment by mrjbq7** [comment]
Btw, thanks @timor for the contribution!

We set Travis CI up as a quick check, but rely on our own build infrastructure to run all the tests (post-commit).  With Travis CI transitioning to a paid service or something soon, we might need to adjust our approach with pre-commit checks.  Github Actions seems pricey, but maybe we can use the "run on our own computers" version of that service.

**Comment by timor** [comment]
Good to know, thanks.

**Pull request merged**
