### PR TITLE
vm: replace line comments // with block comments /**/ for consintency

### LINKED ISSUE #1651: VM C++ comments
For consistency they should all be `/* */` or `//`. It seems like `/* */` is used more often so we should go with that syntax.

### PR DESCRIPTION
**Pull request by AlexIljin**
Fix #1651.

### CODE REVIEW

**Comment by bjourne** [comment]
:+1: Unless John or Doug has objections, let's merge!

**Comment by mrjbq7** [comment]
eww, ``//`` beats ``/* */`` in any rock paper scissors battle.

**Comment by mrjbq7** [comment]
I like consistency, so I leave it to @bjourne to agree and merge. :-)

I'd also be in favor of switching to ``//`` everywhere, but @slavapestov might roll over in his grave.

**Comment by bjourne** [comment]
I also like `//` more. But @AlexIljin has done the hard work of changing all comments to `/* */` so that's good. Someone in the future can update it "back" to `//` everywhere.

**Comment by AlexIljin** [comment]
> Someone in the future can update it "back" to `//` everywhere. 
Maybe that'll be me as well! ; )

**Comment by AlexIljin** [comment]
> might roll over in his grave.

... swiftly!

**Comment by mrjbq7** [comment]
Merged, thanks @AlexIljin !

**Pull request closed without merging**
