### PR TITLE
Charts

### PR DESCRIPTION
**Pull request by AlexIljin**
I'd like to contribute this native Factor implementation of a 2D chart gadget. It's got a minimal feature set, it is well covered by tests, and can easily be extended by other contributors. A demo is supplied, just call                                                                                                                                                                                                                                                                                                                                           `"ui.gadgets.charts.demos" run`, and then resize the window.

The main focus in the initial implementation was made on rendering speed. I consider this to be the first step in replacing R with Factor in the Big Data game. They have the all-powerful `plot` function, which has some simple usability tricks that are actually quite easy to borrow.

### CODE REVIEW

**Comment by jonenst** [comment]
Very nice ! The git history looks very clean and useful, even if it's 60 commits maybe it's good to keep the history.

Also, I couldn't resist hacking it into a control to animate the graph :p ( see http://docs.factorcode.org/content/article-ui-control-impl.html )
```diff
diff --git a/extra/ui/gadgets/charts/demos/demos.factor b/extra/ui/gadgets/charts/demos/demos.factor
index 948051e..5c59c9c 100644
--- a/extra/ui/gadgets/charts/demos/demos.factor
+++ b/extra/ui/gadgets/charts/demos/demos.factor
@@ -1,8 +1,9 @@
 ! Copyright (C) 2017 Alexander Ilin.
 ! See http://factorcode.org/license.txt for BSD license.
 USING: accessors arrays colors.constants kernel literals locals
-math math.constants math.functions sequences ui ui.gadgets
+math math.constants math.functions sequences ui ui.gadgets models^M
 ui.gadgets.charts ui.gadgets.charts.axes ui.gadgets.charts.lines
+calendar threads sequences.extras^M
 ;
 IN: ui.gadgets.charts.demos
 
@@ -20,17 +21,21 @@ CONSTANT: -pi $[ pi neg ]
 
 <PRIVATE
 
+: rotate-sine ( model -- )^M
+    [ value>> flip [ 0 swap [ 1 rotate ] change-nth ] keep flip ] keep set-model ;^M
 :: (chart-demo) ( n -- )
     chart new ${ ${ -pi pi } { -1 1 } } >>axes
-    line new COLOR: blue >>color n sine-wave >>data add-gadget
-    line new COLOR: red >>color n cosine-wave >>data add-gadget
+    line-control new COLOR: blue >>color n sine-wave <model> dup :> sinemodel >>model add-gadget^M
+    line-control new COLOR: red >>color n cosine-wave <model> dup :> cosinemodel >>model add-gadget^M
     vertical-axis new add-gadget
     horizontal-axis new add-gadget
-    "Chart" open-window ;
+    "Chart" open-window^M
+    100 [ sinemodel rotate-sine 100 milliseconds sleep ] times^M
+    ;^M
 
 PRIVATE>
 
-: chart-demo ( -- ) 40 (chart-demo) ;
+: chart-demo ( -- ) 100 (chart-demo) ;^M
 
 MAIN: chart-demo
 
diff --git a/extra/ui/gadgets/charts/lines/lines.factor b/extra/ui/gadgets/charts/lines/lines.factor
index ea03efb..1fb43ab 100644
--- a/extra/ui/gadgets/charts/lines/lines.factor
+++ b/extra/ui/gadgets/charts/lines/lines.factor
@@ -3,7 +3,7 @@
 USING: accessors arrays assocs binary-search colors.constants
 combinators combinators.short-circuit fry kernel locals make
 math math.order math.statistics math.vectors namespaces opengl
-opengl.gl sequences
+opengl.gl sequences models
 specialized-arrays.instances.alien.c-types.float
 splitting.monotonic ui.gadgets ui.gadgets.charts
 ui.gadgets.charts.utils ui.render ;
@@ -12,6 +12,10 @@ IN: ui.gadgets.charts.lines
 ! Data must be a sequence of { x y } coordinates sorted by
 ! non-descending x vaues.
 TUPLE: line < gadget color data ;
+TUPLE: line-control < line ;
+
+M: line-control model-changed
+    swap value>> >>data relayout ;
 
 <PRIVATE
 
```

**Comment by AlexIljin** [comment]
What are all those `^M` at the end of lines? Looks like an artifact from using Emacs...

**Comment by AlexIljin** [comment]
Also, the updated demo is really cool. `line-control` seems very useful in its own right.
I didn't run it, I'm only looking at the diff you provided, but did you forget to rotate the `cosinemodel`?

**Comment by jonenst** [comment]
Hi Alex,
the ^M is the representation of a carriage return character in my terminal. It's there because your file had carriage returns, so I kept the same style of line endings. In the Unix world, there is no carriage return in a newline, only a line feed. That's why it's shown as this ugly ^M. Also for the record, I'm not using emacs, I'm a real programmer ( https://xkcd.com/378/ ).

For cosinemodel, I was just lazy at the end and already had the sine animation so I didn't finish it :)

**Comment by jonenst** [comment]
By the way, yes, you should make all your files use unix line endings. It's what the whole project uses. You have 3 files that use windows CRLF line endings:

$ find extra/ui/gadgets/charts/ -type f | xargs file
extra/ui/gadgets/charts/demos/authors.txt:        ASCII text
extra/ui/gadgets/charts/demos/tags.txt:           ASCII text
extra/ui/gadgets/charts/demos/demos.factor:       ASCII text, with CRLF line terminators
extra/ui/gadgets/charts/axes/axes.factor:         ASCII text, with CRLF line terminators
extra/ui/gadgets/charts/axes/authors.txt:         ASCII text
extra/ui/gadgets/charts/authors.txt:              ASCII text
extra/ui/gadgets/charts/lines/lines.factor:       ASCII text
extra/ui/gadgets/charts/lines/authors.txt:        ASCII text
extra/ui/gadgets/charts/lines/lines-tests.factor: ASCII text
extra/ui/gadgets/charts/lines/lines-docs.factor:  ASCII text, with very long lines
extra/ui/gadgets/charts/tags.txt:                 ASCII text
extra/ui/gadgets/charts/utils/authors.txt:        ASCII text
extra/ui/gadgets/charts/utils/utils.factor:       ASCII text, with CRLF line terminators
extra/ui/gadgets/charts/charts-tests.factor:      ASCII text
extra/ui/gadgets/charts/charts.factor:            ASCII text

**Comment by AlexIljin** [comment]
Yes, I can see that now, and I'm already working on it... : )

**Comment by AlexIljin** [comment]
Done! I have updated the history so that all files now contain the correct line endings.

**Comment by jonenst** [comment]
charts

Gifs are so 2017

**Comment by AlexIljin** [comment]
The cosine should travel in the opposite direction : ))

**Comment by jonenst** [comment]
I like challenges :p Also there was a horizontal line because I was rotating the x coordinate instead of the y coordinate, breaking the requirement on x being ascending

charts


```
: rotate-sine ( model n -- )
    '[ value>> flip [ 1 swap [ _ rotate ] change-nth ] keep flip ] keep set-model ;
```

**Comment by AlexIljin** [comment]
Ha-ha, this is awesome! I love it! : ))

**Comment by erg** [comment]
This is great!!

Is it a bug that the blue line doesn't smoothly cross the X-axis?

**Comment by jonenst** [comment]
It's a bug in my "rotate-sine". The input sequence is not periodic because the first and last values are duplicated. So when rotating it creates this artifact.

**Comment by jonenst** [comment]
Took me long enough (tried byzanz, ffcast, avconv, simplescreenrecorder, ffmpeg; The winning combo is simplescreenrecord + ffmpeg), but I had to do a 60fps gif of this thing :)
out_gimp

Hopefully it display correctly in the browser.. If not, you can still rightclick and download it

**Comment by AlexIljin** [comment]
: ))) Cool stuff, @jonenst, I hope it gets pulled : ))

**Comment by mrjbq7** [comment]
Very cool!  

Should I merge and then apply @jonenst patch?

**Comment by AlexIljin** [comment]
That would be fine with me. Or @jonenst may submit his patch in a separate PR on top of the merge result.

**Comment by mrjbq7** [comment]
Merged, thanks!!

@jonenst if you want to make a patch, that'd be cool.  I wasn't sure where the ``n`` argument for ``rotate-sine`` came from.

**Comment by jonenst** [comment]
Hi,
My patch was not meant to be merged :)
It was just à hack and maybe an Idea for Alex to explore !

Le 17 avr. 2017 21:57, "Alexander Iljin" <notifications@github.com> a
écrit :

**Comment by bpollack** [comment]
So can I close this at this point, @jonenst? Seems like everything we wanted merged in this PR has been.

**Comment by jonenst** [comment]
Yes

Le 26 avr. 2017 00:23, "Benjamin Pollack" <notifications@github.com> a
écrit :

**Pull request closed without merging**
