### PR TITLE
Update to Unicode 13.0

### LINKED ISSUE #2335: Update unicode tables
The tables included with `unicode.data` are for Unicode 5.2, updated 11 years ago:
https://github.com/factor/factor/tree/a84a34c5e2b74e0db8baa81647755a0ae0427425/basis/unicode/data

The latest spec (as of fall 2020) is Unicode 14.0.0, and the tables are available here:
https://unicode.org/onlinedat/online.html

Since `uncode.data` is itself a parser for the official flat file format this should be pretty straightforward. Happy to take a crack at this!

### PR DESCRIPTION
**Pull request by phred**
This updates the Factor unicode tables to the latest version of Unicode. `"unicode" unit-test` passes just fine on a fresh image, not sure if there's anything else that I need to test here.

Fixes #2335 

I will note that we do not seem to ship the emoji data, which are a separate table. Worth creating a unicode.emoji vocab perhaps?

### CODE REVIEW

**Comment by mrjbq7** [comment]
Are there any updates to text files in ``unicode/UCA`` or ``unicode/data`` or the tests in ``unicode/breaks`` or ``unicode/normalize`` or ``unicode/collation``?

**Comment by phred** [comment]
Ah whoops, looks like I missed those files. Will add & re-test. And I was wrong: emoji work just fine and are named when (for example) completing `CHAR: ` forms.

**Comment by mrjbq7** [comment]
Awesome, thanks!!

I just did a ``find unicode | grep txt`` to see where the relevant data files are... seems like they're spread around a bit.

**Comment by phred** [comment]
Yeah I'm seeing the same (data all over the place). It looks like the tests in `unicode/breaks`, `unicode/normalize`, and `unicode/collation` have copies of Unicode 5.2 data from back in 2009… but they seem to be loading the correct resources, for example in `basis/unicode/breaks/break-tests.factor`:

```
breaks/breaks-tests.factor:    "vocab:unicode/UCD/auxiliary/GraphemeBreakTest.txt" ;
breaks/breaks-tests.factor:    "vocab:unicode/UCD/auxiliary/GraphemeBreakTest.txt" ;
breaks/breaks-tests.factor:    "vocab:unicode/UCD/auxiliary/WordBreakTest.txt" ;
breaks/breaks.factor:"resource:basis/unicode/UCD/auxiliary/emoji-data.txt"
breaks/breaks.factor:"resource:basis/unicode/UCD/auxiliary/emoji-data.txt"
breaks/breaks.factor:"resource:basis/unicode/UCD/auxiliary/WordBreakProperty.txt"
```

So, even though we've been shipping newer data I guess those tests still have some old tables lying around—will try to remove those and see if the tests still pass. There's no reason those vocabs can't load everything from `resource:basis/unicode/UCD` (in fact, they seem to already).

Meanwhile have located the updated UCA data: https://www.unicode.org/Public/UCA/13.0.0/

**Comment by phred** [comment]
Removed the old data with no ill consequences. Updated UCA data as well. `"unicode" test` works great with no issues. Please look when you have a chance, @mrjbq7, thanks. (:

**Comment by mrjbq7** [comment]
Awesome!  Merged!!

I show a couple of unicode.collation failures on my mac maybe?

**Comment by mrjbq7** [comment]
Unit Test: { { { } } [ parse-collation-test-weights find-bad-collations ] }

**Comment by mrjbq7** [comment]
Looks like another Tibetan test (the first two) and some other characters:

```
{
    { 4018 3953 1 3968 97 }
    { 4019 3953 1 3968 97 }
    { 101632 33 }
    { 101632 63 }
    { 101632 820 }
    { 101632 97 }
    { 101632 65 }
    { 101632 98 }
    { 101633 33 }
    { 101633 63 }
    { 101633 820 }
    { 101633 97 }
    { 101633 65 }
    { 101633 98 }
    { 101634 33 }
    { 101634 63 }
    { 101634 820 }
    { 101634 97 }
    { 101634 65 }
    { 101634 98 }
    { 101635 33 }
    { 101635 63 }
    { 101635 820 }
    { 101635 97 }
    { 101635 65 }
    { 101635 98 }
    { 101640 33 }
    { 101640 63 }
    { 101640 820 }
    { 101640 97 }
    { 101640 65 }
    { 101640 98 }
    { 101120 33 }
    { 101120 63 }
    { 101120 820 }
    { 101120 97 }
    { 101120 65 }
    { 101120 98 }
    { 101589 33 }
    { 101589 63 }
    { 101589 820 }
    { 101589 97 }
    { 101589 65 }
    { 101589 98 }
    { 40952 33 }
    { 40952 63 }
    { 40952 97 }
    { 40952 65 }
    { 40952 98 }
    { 40953 33 }
    { 40953 63 }
    { 40953 97 }
    { 40953 65 }
    { 40953 98 }
    { 40954 33 }
    { 40954 63 }
    { 40954 97 }
    { 40954 65 }
    { 40954 98 }
    { 40955 33 }
    { 40955 63 }
    { 40955 97 }
    { 40955 65 }
    { 40955 98 }
    { 40956 33 }
    { 40956 63 }
    { 40956 97 }
    { 40956 65 }
    { 40956 98 }
    { 19894 33 }
    { 19894 63 }
    { 19894 97 }
    { 19894 65 }
    { 19894 98 }
    { 19895 33 }
    { 19895 63 }
    { 19895 97 }
    { 19895 65 }
    { 19895 98 }
    { 19896 33 }
    { 19896 63 }
    { 19896 97 }
    { 19896 65 }
    { 19896 98 }
    { 19897 33 }
    { 19897 63 }
    { 19897 97 }
    { 19897 65 }
    { 19897 98 }
    { 19898 33 }
    { 19898 63 }
    { 19898 97 }
    { 19898 65 }
    { 19898 98 }
    { 19899 33 }
    { 19899 63 }
    { 19899 97 }
    { 19899 65 }
    { 19899 98 }
    { 19900 33 }
    { 19900 63 }
    { 19900 97 }
    { 19900 65 }
    { 19900 98 }
    { 19901 33 }
    { 19901 63 }
    { 19901 97 }
    { 19901 65 }
    { 19901 98 }
    { 19902 33 }
    { 19902 63 }
    { 19902 97 }
    { 19902 65 }
    { 19902 98 }
    { 19903 33 }
    { 19903 63 }
    { 19903 97 }
    { 19903 65 }
    { 19903 98 }
    { 173785 33 }
    { 173785 63 }
    { 173785 820 }
    { 173785 97 }
    { 173785 65 }
    { 173785 98 }
    { 173786 33 }
    { 173786 63 }
    { 173786 820 }
    { 173786 97 }
    { 173786 65 }
    { 173786 98 }
    { 173787 33 }
    { 173787 63 }
    { 173787 820 }
    { 173787 97 }
    { 173787 65 }
    { 173787 98 }
    { 173788 33 }
    { 173788 63 }
    { 173788 820 }
    { 173788 97 }
    { 173788 65 }
    { 173788 98 }
    { 173789 33 }
    { 173789 63 }
    { 173789 820 }
    { 173789 97 }
    { 173789 65 }
    { 173789 98 }
    { 196608 33 }
    { 196608 63 }
    { 196608 820 }
    { 196608 97 }
    { 196608 65 }
    { 196608 98 }
    { 196609 33 }
    { 196609 63 }
    { 196609 820 }
    { 196609 97 }
    { 196609 65 }
    { 196609 98 }
    { 201546 33 }
    { 201546 63 }
    { 201546 820 }
    { 201546 97 }
    { 201546 65 }
    { 201546 98 }
}
```

**Comment by mrjbq7** [comment]
Okay!  Fixed for unicode 13.0 changes.

b86da3090ab5a5136bc00ca3a6b5495fa19bdd8d

Thanks @phred !!

**Comment by phred** [comment]
Hmm, not sure why those tests passed here—thanks for the quick fix!

**Pull request merged**
