### PR TITLE
vm/master.hpp: optional reproducible VM compilation

### PR DESCRIPTION
**Pull request by catb0t**
The old behaviour of building with `__DATE__` and
    `__TIME__` is still the default, but now it's
    possible to use `-DREPRODUCIBLE=1` and the
    `REPRODUCIBLE=1` parameter to `make` and `nmake`.

Specifically, this replaces the value of
    `FACTOR_COMPILE_TIME` with the string constant
    `"[reproducible]"`. This is purely a cosmetic
    change, since `vm-compile-time` is never parsed.

### CODE REVIEW

**Comment by catb0t** [comment]
Here's a test script: 
```bash
#! /bin/bash
build_factor () {
  { command rm factor; make clean; make ; } # >/dev/null
}
build_repro_factor () {
  { command rm factor; make clean; make REPRODUCIBLE=1 ; } # >/dev/null
}
build_factor
sum1_1="$(sha256sum factor | cut -d' ' -f1)"
build_factor
sum1_2="$(sha256sum factor | cut -d' ' -f1)"
build_repro_factor
sum2_1="$(sha256sum factor | cut -d' ' -f1)"
build_repro_factor
sum2_2="$(sha256sum factor | cut -d' ' -f1)"
if [ $sum1_1 == $sum1_2 ]
then
  echo "normal build sums MATCH"
else
  echo "normal build sums don't match"
fi
if [ $sum2_1 == $sum2_2 ]
then
  echo "reproducible sums MATCH"
else
  echo "reproducible sums don't match"
fi
```
of which the output is `normal build sums don't match / reproducible sums MATCH`.

**Comment by catb0t** [comment]
Hm, this can be done entirely with `make SITE_CFLAGS="-D__DATE__='\"[reproducible]\"' -D__TIME__='\"\"'"`, which I thought wouldn't work.

If this isn't of interest to anyone else, it can be closed, unless it adds value being in mainline.

**Comment by erg** [comment]
Looks good, I'll merge it.

What's your use case for reproducible builds for Factor?

**Comment by erg** [comment]
Actually, it's spewing warnings on macOS.

This turns it off for ``clang``: ``make SITE_CFLAGS="-D__DATE__='\"[reproducible]\"' -D__TIME__='\"\"' -Wno-builtin-macro-redefined"``

I guess if we only turned it off for reproducible builds that would be fine. Is there another way?

```
% make SITE_CFLAGS="-D__DATE__='\"[reproducible]\"' -D__TIME__='\"\"'"
/Applications/Xcode.app/Contents/Developer/usr/bin/make `./build.sh make-target`
/Applications/Xcode.app/Contents/Developer/usr/bin/make factor factor-ffi-test factor-lib macosx.app CONFIG=vm/Config.macosx.x86.64
c++ -c -x c++-header -Wall -pedantic -DFACTOR_VERSION="0.99" -DFACTOR_GIT_LABEL="heads/master-044f7bbe11db26fc98580d1f6a84af35b04740b4" -DFACTOR_REPRODUCIBLE="0" -D__DATE__='"[reproducible]"' -D__TIME__='""' -O3 -std=c++11 -o vm/master.hpp.gch vm/master.hpp
In file included from <built-in>:391:
<command line>:4:9: warning: redefining builtin macro [-Wbuiltin-macro-redefined]
#define __DATE__ "[reproducible]"
        ^
<command line>:5:9: warning: redefining builtin macro [-Wbuiltin-macro-redefined]
#define __TIME__ ""
        ^
2 warnings generated.
c++ -c -Wall -pedantic -DFACTOR_VERSION="0.99" -DFACTOR_GIT_LABEL="heads/master-044f7bbe11db26fc98580d1f6a84af35b04740b4" -DFACTOR_REPRODUCIBLE="0" -D__DATE__='"[reproducible]"' -D__TIME__='""' -O3 -std=c++11 -o vm/main-unix.o vm/main-unix.cpp
In file included from <built-in>:391:
<command line>:4:9: warning: redefining builtin macro [-Wbuiltin-macro-redefined]
#define __DATE__ "[reproducible]"
        ^
<command line>:5:9: warning: redefining builtin macro [-Wbuiltin-macro-redefined]
#define __TIME__ ""
        ^
2 warnings generated.
c++ -c -Wall -pedantic -DFACTOR_VERSION="0.99" -DFACTOR_GIT_LABEL="heads/master-044f7bbe11db26fc98580d1f6a84af35b04740b4" -DFACTOR_REPRODUCIBLE="0" -D__DATE__='"[reproducible]"' -D__TIME__='""' -O3 -std=c++11 -o vm/os-unix.o vm/os-unix.cpp
In file included from <built-in>:391:
<command line>:4:9: warning: redefining builtin macro [-Wbuiltin-macro-redefined]
#define __DATE__ "[reproducible]"
        ^
<command line>:5:9: warning: redefining builtin macro [-Wbuiltin-macro-redefined]
#define __TIME__ ""
```

**Comment by erg** [comment]
Ok I fixed it up some. Please let me know if anything's broken.

**Comment by catb0t** [comment]
Thanks for merging! I pulled master and it works perfectly. 

> What's your use case for reproducible builds for Factor? 

To get the same checksum from consecutive compiles, so that they can be easily checked for consistency / up-to-dateness for a given branch / version of the source code -- for easily having many compiled versions of Factor at once. 
https://github.com/catb0t/multifactor/tree/master/README.md

And sorry for confusing you, I meant that `make SITE_CFLAGS=...` command does the same thing as this whole commit, but in a more hacky way that makes warnings. 

It's only necessary to use `REPRODUCIBLE=1` ***or*** change the definitions of `__DATE__` and `__TIME__`, and only when redefining `__DATE__`/`__TIME__` is it necessary to use `-Wno-builtin-macro-redefined`. 

Using `make REPRODUCIBLE=1` can't generate warnings about redefining macros because we avoid them entirely, so `-Wno-builtin-macro-redefined` isn't needed.

**Pull request closed without merging**
