### PR TITLE
Add: glfw3 bindings & Init: vulkan bindings

### PR DESCRIPTION
**Pull request by TriedAngle**

### CODE REVIEW

**Comment by TriedAngle** [comment]
Here some demo code
```
USING: glfw.ffi math.parser io.encodings.utf8 alien.strings calendar threads ;

: TestCallback ( -- alien )
  [| window key scancode action mods |
    key GLFW_KEY_ESCAPE = [ window 1 glfwSetWindowShouldClose ] when
  ] GLFWkeyfun ;

glfwInit [ "error init\n" write ] unless
200 300 "hello" utf8 string>alien nullptr nullptr glfwCreateWindow
dup TestCallback glfwSetKeyCallback drop
[ dup glfwWindowShouldClose 0 = ] [ glfwPollEvents 10 milliseconds sleep ] while
glfwDestroyWindow
glfwTerminate
```

**Comment by mrjbq7** [comment]
What do you use the nullptr word for? I wouldn’t think that’s necessary. On Jun 19, 2023, at 8:39 PM, TryAngle ***@***.***> wrote:﻿
Here some demo code
USING: glfw.ffi math.parser io.encodings.utf8 alien.strings calendar threads ;

: TestCallback ( -- alien )
  [| window key scancode action mods |
    key GLFW_KEY_ESCAPE = [ window 1 glfwSetWindowShouldClose ] when
  ] GLFWkeyfun ;

glfwInit [ "error init\n" write ] unless
200 300 "hello" utf8 string>alien nullptr nullptr glfwCreateWindow
dup TestCallback glfwSetKeyCallback drop
[ dup glfwWindowShouldClose 0 = ] [ glfwPollEvents 10 milliseconds sleep ] while
glfwDestroyWindow
glfwTerminate

**Comment by TriedAngle** [comment]
it's in there by accident, used it personally. I'll remove it

**Comment by mrjbq7** [comment]
Thanks!

**Pull request merged**
