### PR TITLE
Update Raylib from 2.5 -> 3.5

### PR DESCRIPTION
**Pull request by ArnautDaniel**
Just a bindings update.  Adds some new functions, and changes some minor things to be compatible with the latest Raylib.

### CODE REVIEW

**Comment by ArnautDaniel** [comment]
https://github.com/raysan5/raylib/releases

For anyone that's interested you can read the changelog here.

**Comment by mrjbq7** [comment]
Cool! Thanks!

Is there any good way to add a test suite to test basic functionality?

**Comment by ArnautDaniel** [comment]
I can look into that for sure.

**Comment by mrjbq7** [comment]
You might want to update the link here:

https://github.com/raysan5/raylib/blob/master/BINDINGS.md

**Comment by ArnautDaniel** [comment]
I'll take care of it.  I'm gonna finish updating my gforth version (3.0 -> 3.5) tomorrow and then submit it as one pull request to update both links.  :+1:

**Comment by mrjbq7** [comment]
Thanks for the contribution!!

**Pull request merged**
