### PR TITLE
Replace image-reliant UI components

### PR DESCRIPTION
**Pull request by inivekin**
I think it may be nice to change some common use ui.gadgets that rely on images to use opengl drawn gadgets instead -makes them more theme-able and tweakable. So all the .tiff images in basis/ui/theme/images aren't used with the default pens in this change.

The change to the slider is easily viewable via the browser, the changes to checkboxes, radio-buttons and border-buttons are easily viewable by the deploy tool. 

Some problems with this  pull request:
1. the change to `on-leave` in the gtk2 backend
    - Logically it made sense to have `forget-rollover` in there but, using the gesture-logger, it was always causing a mouse-leave gesture after a button-up even though the mouse wasn't leaving the gadget. I don't understand why mouse-leave behaves more appropriately without it. I could remove the width increase on the slider hover (which was behaving awkward due to the erroneous mouse-leave), revert the change to on-leave and continue pretending the quirk doesn't exist, if desired. 
2. I went for some minimal shapes/colours and didn't extensively check themes.
    - can make things (specifically the checkmarks) more obvious by drawing a more unique shape or a size change.

I take no issue with this being declined/altered at will, this is only a suggestion.

### CODE REVIEW

**Comment by mrjbq7** [comment]
This is cool! I need to understand the GTK issue before merging it, give me some time to be able to do that, thanks!

**Comment by inivekin** [comment]
> give me some time to be able to do that

If there is grunt work here I could do in your stead let me know - I'm just unfamiliar with GUI stuff so don't really know where/how to start debugging such a large event-driven library.
My hunch is to try log to a file whatever functions are sending mouse-leave to compensate for the one I removed, or maybe investigate what gtk2 is doing on mouse up that may also trigger the on-leave connection?

**Comment by mrjbq7** [comment]
Hi @inivekin i haven't forgotten about this, need to still look into the GTK thing, but have been busy.  Next few days, I hope!

**Comment by mrjbq7** [comment]
Still not sure about rollover, but perhaps leaning towards not having sliders grow/shrink anyway?

**Comment by mrjbq7** [comment]
There's an issue with sliders not being fixnum, see for example ``"boids" run``, also the grow/shrink looks weird in that use case.

**Comment by inivekin** [comment]
> There's an issue with sliders not being fixnum, see for example `"boids" run`, also the grow/shrink looks weird in that use case.

I see. The scaling on hover does appear more trouble than it is worth. Removing it prevents this non-fixnum error as dimensions are no longer going through any of the unnecessary scaling math.

I was motivated to do the scaling thing because I felt uneasy about just giving it a fixed width (and various other apps do the scale on hover thing) but I guess no change in width was how it was handled before so I was fretting over nothing.

**Comment by mrjbq7** [comment]
Any thoughts on removing the image-based buttons? Or just making this the default?

Visually, we probably need more contrast between the "clicked" and not clicked colors.

**Comment by mrjbq7** [comment]
Probably the radio / checkboxes would be good with an outline, transparent inside, then a darker clicked square inside.  I like keeping them simple, maybe circles instead of diamonds for radio, but honestly fine with whatever !

**Comment by inivekin** [comment]
> Any thoughts on removing the image-based buttons? Or just making this the default?
> 
> Visually, we probably need more contrast between the "clicked" and not clicked colors.

I didn't want to completely remove the code for the image-based ones because they are a useful reference should someone want to do something with that - maybe I should move them into separate files?
At first I thought this could also be a 'themeable' choice but didn't have a personal interest in making themes more complex than colours.

I also changed the colours to use error-type colours because they seem to be the most reliably highlighted across themes.
various-checkbox-themes

> Probably the radio / checkboxes would be good with an outline, transparent inside, then a darker clicked square inside. I like keeping them simple, maybe circles instead of diamonds for radio, but honestly fine with whatever !

Will try to add some more complicated colours/shapes as you described to the checkmark/radio buttons in the coming days. Though I personally like the bare-minimum styling, this fairly simple pull-request is still changing some pretty common gadgets so I don't intend to impose a style others wouldn't prefer.

**Comment by mrjbq7** [comment]
> Will try to add some more complicated colours/shapes as you described to the checkmark/radio buttons in the coming days. Though I personally like the bare-minimum styling, this fairly simple pull-request is still changing some pretty common gadgets so I don't intend to impose a style others wouldn't prefer.

I like minimal, I only mentioned it to make it more obvious which is selected. Might not be worth spending a lot of time on?

I had changed the tabbed gadget to also not use images, and also be minimal, and I think it turned out nicely.

**Comment by mrjbq7** [comment]
I still have the issue with ``"boids" run`` giving float errors.

The arrows also look a little bad on that demo, and the buttons are super dark?

**Comment by inivekin** [comment]
> I still have the issue with `"boids" run` giving float errors.
> 
> The arrows also look a little bad on that demo, and the buttons are super dark?

I can't seem to get the floating point errors since I removed the scaling (which I pretty easily reproduced). Are you getting the float errors by just click-dragging a slider or clicking the arrows? Has it just become more rare than previous or the same?

I guess you mean the arrows looking bad is because the arrow background is different to the application background?
I've added a commit that changes buttons to use the content-background and toolbar colors instead, that seems sort of ok? Maybe not differentiated from the background enough?

[boids-theme-light.webm](https://github.com/user-attachments/assets/328b2382-e90c-4d2b-9703-044e63e32000)
[boids-theme-dark.webm](https://github.com/user-attachments/assets/90f2ed0b-fc19-44ab-b8e1-799ffd7bd297)
[boids-theme-wombat.webm](https://github.com/user-attachments/assets/fc0df6c7-1644-412c-90e6-1b64c058402b)

What would you say to me sneaking in a patch in this pull that makes all of the boids app actually follow the theme, as below
[boids-theme-light-theme.webm](https://github.com/user-attachments/assets/0f265a30-5d3f-4bda-9ffb-a089d7e818f7)
[boids-theme-greenscreen.webm](https://github.com/user-attachments/assets/9a24acac-93d2-4ea0-8bc4-eb1c04067041)
```
diff --git a/extra/boids/boids.factor b/extra/boids/boids.factor
index d3dc17e133..061f10bd7d 100644
--- a/extra/boids/boids.factor
+++ b/extra/boids/boids.factor
@@ -49,7 +49,7 @@ M: boids-gadget ungraft*
     ] with-translation ;
 
 : draw-boids ( boids -- )
-    0.0 0.0 0.0 0.5 glColor4f
+    details-color >rgba-components drop 0.5 glColor4f
     [ draw-boid ] each ;
 
 M: boids-gadget draw-gadget* ( boids-gadget -- )
@@ -97,7 +97,7 @@ M: range-observer model-changed
 
     { 5 5 } <border> white-interior
 
-    behavior class-of name>> COLOR: gray <framed-labeled-gadget> ;
+    behavior class-of name>> heading-color <framed-labeled-gadget> ;
 
 :: set-population ( n boids-gadget -- )
     boids-gadget [
@@ -145,7 +145,7 @@ PRIVATE>
 
     { 5 5 } <border> add-gadget
 
-    "simulation" COLOR: gray <framed-labeled-gadget> ;
+    "simulation" heading-color <framed-labeled-gadget> ;
 
 TUPLE: boids-frame < pack ;
 
@@ -171,4 +171,4 @@ boids-frame "touchbar" f {
 } define-command-map
 
 MAIN-WINDOW: boids { { title "Boids" } }
-    <boids-frame> >>gadgets ;
+    <boids-frame> white-interior >>gadgets ;
```

Also whoops, accidentally rebased and pushed fixing...

**Comment by mrjbq7** [comment]
I love the idea of boids respecting the theme! Please do!

I'll refresh and check again the float error, maybe my branch didn't have your updates.

**Comment by mrjbq7** [comment]
The only style thing I might suggest is making the slider take less vertical space in the boids case (where it's horizontal).

If we wanted to, we could curve the sides like the current slider, but that's more GL instructions...

**Comment by mrjbq7** [comment]
As an aside, I still find it hilarious ``white-interior`` is used to theme it.  Someday maybe we should rename that.

**Comment by mrjbq7** [comment]
I made sure I have your latest 

```
commit 5a31d5a8e3b887bc3e87e31308439061551195c7 (HEAD -> replace-bitmap-ui-components, inivekin/replace-bitmap-ui-components)
Author: inivekin <inivekin@gmail.com>
Date:   Sun Aug 18 09:57:35 2024 +0800

    Changes use of dim-color to content-background and toolbar colors

commit daa68a032d86bb4027dd71c7eb67ca2e2fc8be78
Author: inivekin <inivekin@gmail.com>
Date:   Sun Aug 11 09:11:28 2024 +0800

    Changes button selected color to be obvious across various themes

commit 12cc7fa93fea3276b5dbbd9bbf162768c516d13d
Author: inivekin <inivekin@gmail.com>
Date:   Sat Aug 10 17:19:05 2024 +0800

    Reverts unexplained gtk on-leave change
```

and then i still get the error when i click on the slider and drag:

Screenshot 2024-08-17 at 8 36 28 PM

**Comment by mrjbq7** [comment]
Wait, maybe this error happens on master branch too, in the ``population`` slider.

**Comment by mrjbq7** [comment]
Okay, thats fixed in 09a49c27de3ebabc58c5356269f165470d2bfaa4.

**Comment by inivekin** [comment]
> The only style thing I might suggest is making the slider take less vertical space in the boids case (where it's horizontal).
> 
> If we wanted to, we could curve the sides like the current slider, but that's more GL instructions...

For the vertical space it is taking, it currently just takes up as much vertical space as it is given by the parent gadget layout (with the size of the arrows being the minimum).
```
USE: boids QUALIFIED-WITH: models.range mr
2 0 0 180 1 mr:<range> dup [ drop ] connect horizontal <slider> "test" open-window
```

Do you want that to not be universal behaviour or should I just make the specific tweak for boids to make it thinner (i.e. chuck the <slider>s in a <border>) ?

**Comment by mrjbq7** [comment]
Hi @inivekin did you have any thoughts on anything else you'd like to add or is this ready for review and merging?

**Comment by inivekin** [comment]
> Hi @inivekin did you have any thoughts on anything else you'd like to add or is this ready for review and merging?
> 

I was thinking of adding a rounded rectangle pen in ui.pens so I could round off the corners of movable bits.
Maybe that could be a second pull so this one isn't hanging around, I'm not sure when I'll get to it.

**Comment by mrjbq7** [comment]
Okay I rebased this branch on git master to check it out, some thoughts:

* Buttons no longer look like buttons, they at should probably have button outlines or backgrounds not just hover states.

* The slider is a little bit light gray on the light theme, and I wonder if we should use one of the darker colors since it was previously black-ish for better contrast.

* In ``"color-table" run`` for some reason the sliders don't position properly on the lower right and the right most horizontal arrow is pretty unclickable... 

I like it!

I do think we should probably remove the image based buttons when we are happy with this!

**Comment by inivekin** [comment]
- Was it specifically the scrollbar buttons that you wanted more obvious with outlines or does the issue extend to other button types? I've added in some lines for the scroll buttons to make it look more button-y
- High contrast default makes sense, I centralized the color to a `slider-highlight-color` word to make it easier to change it for contrast and made it `dim-color` instead of `line-color` (will keep it line color in my .factor-rc as I like the low contrast myself) 
20241004_18h13m22s_grim

About the `"color-table" run` issue, I'm not sure I'm getting the same behaviour (I have rebased with master but maybe I need to use a cleaner image or something?)
20241004_18h15m13s_grim
20241004_18h15m27s_grim
Is your bottom scroller offset in comparison to mine?

It doesn't sound like what you were describing, but I could get it to hide the vertical scroller like the following, but I think that is because the vertical scroller is with the search-table inside a viewport, so the vertical hides because it is part of a different internal viewport.
20241004_18h16m16s_grim

Will excise the unused image-theme constructors and pens this weekend. Thanks for the feedback.

**Comment by mrjbq7** [comment]
Hmm, i do like ``line-color`` better than ``dim-color``, but for some reason it looked brighter than that even, more like ``toolbar-background``.

I didn't mean those dividers, alhtough thats cool, what I meant was the buttons on things like ``"demos" run`` or ``"calc-ui" run`` or ``"boids" run``.

**Comment by mrjbq7** [comment]
For example, older Factor:



Factor 0.100:

Screenshot 2024-10-04 at 9 55 15 AM

Factor 0.101 (this branch):

Screenshot 2024-10-04 at 9 56 20 AM

**Comment by mrjbq7** [comment]
Fixed the double ``<scroller>`` issue in color-table in 88798b0ecea97b09fc54fe419752a3e67157bb6e

**Comment by inivekin** [comment]
1. added a `<filled-border>` gadget around `<border-button>`, seems to work well with the apps you have mentioned in this thread previously. I thnk
20241006_09h59m18s_grim
3. removed the code no longer used
4. Not sure about the color looking slightly lighter, if I run `"a long label that will overflow and create a scrollbar when window resized" <label> line-color <solid> >>interior <scroller> "test" open-window` it seemed to match. Maybe it was a thing with the theme switching not changing everything on a reload? I don't know if the way I use `$` in `CONSTANTS:` might cause weirdness there?

**Comment by mrjbq7** [comment]
Merged!

We should probably tweak the slider a smidge to look "cooler" but this is great, maybe rounded edges, maybe small grabber in the middle like the images had.

I removed ``ui.theme.images`` now that it's all color based.

Thanks!

**Pull request closed without merging**
