### PR TITLE
ui.text: simplify code by removing a type test and using if-empty

### PR DESCRIPTION
**Pull request by AlexIljin**
Remove the PRIVATE section of the vocab. Replace an inline type check with dynamic dispatch.

### CODE REVIEW

**Comment by mrjbq7** [comment]
I think you lost the short circuit for empty? Strings.

**Comment by mrjbq7** [comment]
Ah, never mind. I see what you did with if-empty.

**Comment by AlexIljin** [comment]
This patch is not working. For a reason I can't yet grasp, the Listener stops drawing the selection in the input field. Easy to test: type some text and press `C-a`. If the entered text appears selected, everything is OK. With this patch the text doesn't look selected.

**Comment by AlexIljin** [comment]
OK, I understood the reason why the selection wasn't displayed correctly with this patch. The texture cache must get the `selection` object to draw it different from the plain `string`, and with this patch it always got the `string`, so it drew `selection` the same way it remembered to draw the initial string (because the plain text always gets to be displayed before its selected version, and sits in the cache afterwards).

If I disable caching (to prevent #1978 from happening), this patch works as expected.

**Comment by AlexIljin** [comment]
Oops, sorry for reopening.

**Pull request closed without merging**
