### PR TITLE
(fix Travis) furnace.auth docs: #2050 load needed vocabs; don't load extra

### LINKED ISSUE #2050: Travis has been failing `./factor -run=zealot.cli-changed-vocabs | paste -s -d " " -` recently
All the recent pull requests have failed the Linux CI with the message:

```
The command "./factor -run=help.lint `./factor -run=zealot.cli-changed-vocabs | paste -s -d " " -`" exited with 1.
```

but without any error from Factor. 

Search this full build log or any other recent Linux one for `exited with 1`: https://api.travis-ci.org/v3/job/417495274/log.txt

### PR DESCRIPTION
**Pull request by catb0t**
closes #2050

### CODE REVIEW

**Comment by erg** [comment]
Doesn't ``auto-use`` with an empty ``USING:`` list trim these vocabs off again since they aren't directly needed? Let's find a way to change the docs so that clicking on an unloaded vocabulary can load it or load just the docs instead.

**Comment by mrjbq7** [comment]
Why are they needed?

$vocab-link can still link to an unloaded vocab.

**Comment by erg** [comment]
Because of #2050 when zealot runs tests without calling ``load-all`` we get these messages.

**Comment by erg** [comment]
So the fix is to use ``$vocab-link`` instead of ``$link`` I guess?

**Comment by mrjbq7** [comment]
Well if linking to something concrete then the using should add it with auto-use.

**Comment by catb0t** [comment]
It's because of `$subsections "vocab-name"` though, `$link` is not the problem source. Should there be a `$vocab-subsection`?

**Pull request closed without merging**
