### PR TITLE
Boolean expr

### PR DESCRIPTION
**Pull request by AlexIljin**
Resurrect `boolean-expr` from the unmaintained, add documentation.

### CODE REVIEW

**Comment by mrjbq7** [comment]
That's cool.  Saw your comment on cnf, do you think it's busted or..?

**Comment by AlexIljin** [comment]
It's either incorrectly implemented in the first place (inverted logic or something like that) or I don't understand its output.

**Comment by AlexIljin** [comment]
Judging by this code:
```
METHOD: satisfiable? { □ }
    cnf [ (satisfiable?) ] any? ;
```
I think `cnf` should be renamed `dnf`. Otherwise instead of `any?` there would have been `all?`.
What do you think?

**Comment by AlexIljin** [comment]
Yeah, I'm pretty confident now. Both its output and the `satisfiable?` implementation make sense only if `cnf` produces DNF. I have renamed it accordingly and updated the documentation.

**Comment by mrjbq7** [comment]
Cool. Want to have a go at making a working CNF?

**Comment by AlexIljin** [comment]
No, thank you! : ))

**Comment by AlexIljin** [comment]
I worked a little bit on reviving `bubble-chamber`, but got stuck at the multi-method dispatch syntax.

**Comment by erg** [comment]
They're in ``unmaintained/`` for a reason ;)

**Comment by AlexIljin** [comment]
Multi-methods are in extra, and there was a custom (better?) syntax vocab on top of that in unmaintained (`multi-method-syntax`), but I have no experience working with the parser.

**Comment by mrjbq7** [comment]
Merged, thanks!

**Comment by mrjbq7** [comment]
Since you mentioned it, I resurrected ``bubble-chamber`` and ``frame-buffer`` which it depended on from unmaintained.

It draws stuff but seems to have an issue on retina displays.

**Pull request closed without merging**
