### PR TITLE
Allow specifying vocabulary roots on the command line

### LINKED ISSUE #1498: Allow new roots to be specified on the command-line
We have the ``.factor-roots`` file and the ``FACTOR_ROOTS`` environment variable, but there is a use-case that would be nice to have roots specified on the command-line, something like:

```
factor -roots="~/foo:~/baz" blah.factor
```

See, for example the discussion here:

https://github.com/kanaka/mal/pull/98#issuecomment-152253257

### PR DESCRIPTION
**Pull request by bpollack**
Fixes #1498

### CODE REVIEW

**Comment by mrjbq7** [comment]
Probably should use a different split character on Windows:

```
os windows? ";" ":" ?
```

**Comment by mrjbq7** [comment]
Also, if we merge this, it should be documented in ``basis/command-line/startup/startup.factor`` in ``cli-usage``.

**Comment by mrjbq7** [comment]
And in ``README.md`` maybe since that copies the ``cli-usage``.

**Comment by erg** [comment]
Needs unit tests, docs, and maybe we should make it ``-root=foo -root=bar`` instead of using a separator so it's cross-platform, as john pointed out?

**Comment by mrjbq7** [comment]
Can't do ``-root=foo -root=bar`` because command-line doesn't work that way, it just sets the key/values so the last overwrites the first.

**Comment by bpollack** [comment]
I'll add unit tests, docs, and make it use `;` on Windows and `:` on everything else, but @mrjbq7 just pointed out why I went with the splitting in the first place. Obviously that's still doable, but that version requires a VM change.

**Comment by erg** [comment]
We control the implementation of command-line so we could make it work however we want!

But yeah that's more work.

**Comment by bpollack** [comment]
Oh, I thought that the command-line parsing was in the VM for some reason. In that case, yeah, it's more doable. Strong preferences? Do we really want to special-case `-root`?

**Comment by mrjbq7** [comment]
I'd prefer not to special case, although you could "generalize" it by making any conflicting keys append in some standard way, but that seems a little hokey.

So, I don't mind the way you're doing it.

**Comment by bpollack** [comment]
Now with docs and unit tests. Anything else blocking a merge?

**Comment by erg** [comment]
Merged! Thanks!!!!

**Pull request closed without merging**
