### PR TITLE
furance.recaptcha: update to reCAPTCHA2

### PR DESCRIPTION
**Pull request by bpollack**
I'm not honestly 100% sure if I'm testing this right. @erg , do you remember what your original behavior was?

As a sidebar, this currently doesn't handle multiple recaptchas. I feel as if it ought to, but I'm just trying to restore site operation thus far.

### CODE REVIEW

**Comment by bpollack** [comment]
This theoretically fixes #1991 and #2045 BTW.

**Comment by bpollack** [comment]
(Also, I'll test this out more thoroughly in a bit if I have a second; just, this week ended up a bit nuts.)

**Comment by bpollack** [comment]
@mrjbq7 I did not, but will have a chance to tomorrow, and will ping you if it all checks out. Sorry for the delay; between hurricane excitement and other stuff, this got on the backburner.

**Comment by bpollack** [comment]
@mrjbq7 This works and I think it's done; happy to merge if you're good with it.

**Comment by bpollack** [comment]
Er, last patch (one I just pushed); some stuff was hanging in the index there.

**Comment by bpollack** [comment]
And now with minimal unit tests.

**Comment by mrjbq7** [comment]
Merged! @erg  still needs to deploy to concatenative/factorcode.

**Pull request closed without merging**
