### PR TITLE
Dotted pair notation

### PR DESCRIPTION
**Pull request by kusumotonorio**
I want to be able to use the equivalent of the Lisp's list dotted notation for the Factor list.

The PR allows for the following:
```Factor
IN: scratchpad USE: lists
IN: scratchpad L{ 1 2 . 3 } .
L{ 1 2 . 3 }
IN: scratchpad "a" "b" cons "c" cons .
L{ L{ "a" . "b" } . "c" }
IN: scratchpad L{ 1 . L{ 2 . L{ 3 . L{ 4 . L{ 5 . L{ } } } } } } .
L{ 1 2 3 4 5 }
```

This change also allows dots to be elements of lists.
```Factor
IN: scratchpad L{ \ . . \ . } [ car ] [ cdr ]  bi . .
\ .
\ .
```

### CODE REVIEW

**Comment by mrjbq7** [comment]
What does Lisp do with you have multiple dots?

```factor
IN: scratchpad L{ 1 . . . . . 2 }
L{ 1 . 2 }
```

I merged your patches with a small change in 83e46eb030e5fa08c8b3d9d699a4f1e953130140 to fix a bootstrap issue with ``(parse-list-literal)``.

**Comment by kusumotonorio** [comment]
That will be errors.
```scheme
gosh> '( 1 . . . . . 2)         
*** READ-ERROR: Read error at "(standard input)":line 1: dot in wrong context
Stack Trace:
_______________________________________
  0  (read)
        at "/usr/local/Cellar/gauche/0.9.7/share/gauche-0.97/0.9.7/lib/gauche/interactive.scm":236
gosh> *** READ-ERROR: Read error at "(standard input)":line 1: dot in wrong context
Stack Trace:
_______________________________________
  0  (read)
        at "/usr/local/Cellar/gauche/0.9.7/share/gauche-0.97/0.9.7/lib/gauche/interactive.scm":236
gosh> *** READ-ERROR: Read error at "(standard input)":line 1: dot in wrong context
Stack Trace:
_______________________________________
  0  (read)
        at "/usr/local/Cellar/gauche/0.9.7/share/gauche-0.97/0.9.7/lib/gauche/interactive.scm":236
gosh> *** READ-ERROR: Read error at "(standard input)":line 1: dot in wrong context
Stack Trace:
_______________________________________
  0  (read)
        at "/usr/local/Cellar/gauche/0.9.7/share/gauche-0.97/0.9.7/lib/gauche/interactive.scm":236
gosh> 2
gosh> *** READ-ERROR: Read error at "(standard input)":line 1: extra close parenthesis `)'
Stack Trace:
_______________________________________
  0  (read)
        at "/usr/local/Cellar/gauche/0.9.7/share/gauche-0.97/0.9.7/lib/gauche/interactive.scm":236
gosh> 
```

There can be at __most one dot__ in the same hierarchy in a list.
Also, there must __always be one element__ after the dot.
So I should have done the following.

```Factor
ERROR: list-syntax-error ;

<PRIVATE
:: (parse-list-literal) ( accum right-of-dot? -- accum )
    accum scan-token {
        { "}" [ NIL , ] }
        { "." [ right-of-dot? [
                    list-syntax-error
                ] [
                    t (parse-list-literal)
                ] if ] }
        [
            parse-datum dup parsing-word? [
                V{ } clone swap execute-parsing first
            ] when
            , right-of-dot? [ ")" expect ] [ f (parse-list-literal) ] if ]
    } case ;
```

**Comment by mrjbq7** [comment]
Fixed in 20f0b8aa28273737458730659e892987451e53b5.

**Comment by kusumotonorio** [comment]
I found another issue. I think the following input should also result in an error.
```Factor
L{ . 3 }

--- Data stack:
3
```
On Scheme:
```Scheme
gosh> '( . 3)
*** READ-ERROR: Read error at "(standard input)":line 1: bad dot syntax
Stack Trace:
_______________________________________
  0  (read)
        at "/usr/local/Cellar/gauche/0.9.7/share/gauche-0.97/0.9.7/lib/gauche/interactive.scm":236
gosh> 3
gosh> *** READ-ERROR: Read error at "(standard input)":line 1: extra close parenthesis `)'
Stack Trace:
_______________________________________
  0  (read)
        at "/usr/local/Cellar/gauche/0.9.7/share/gauche-0.97/0.9.7/lib/gauche/interactive.scm":236
```
 
What about the following code?
```Factor
USE: namespaces

: (parse-list-literal) ( right-of-dot? -- )
    scan-token {
        { "}" [ drop +nil+ , ] }
        { "." [ [ list-syntax-error ] when
                building get empty? [ list-syntax-error ] [   ! <---
                    t (parse-list-literal)
                ] if ] }
        [
            parse-datum dup parsing-word? [
                V{ } clone swap execute-parsing first
            ] when
            , [ "}" expect ] [ f (parse-list-literal) ] if
        ]
    } case ;
```

**Comment by mrjbq7** [comment]
Fixed in 08dd854b15926cc8cb6928f2d271d8bfbb637b48.

**Pull request closed without merging**
