### PR TITLE
Windows registry

### PR DESCRIPTION
**Pull request by AlexIljin**
Hey, guys! I've added a new word that allows you to set values in the Windows registry. What do you think?

### CODE REVIEW

**Comment by mrjbq7** [comment]
Any chance you could make a test for that?  like flip-flop a registry value, or increment, or something?

**Comment by AlexIljin** [comment]
An example usage would be something like this:
```
USING: windows.registry windows.advapi32 fry ;
: add-to-PATH ( path -- )
    [ HKEY_CURRENT_USER "Environment" "Path" ] dip
    '[ _ ";" glue ] change-registry-value ; 
```
There is no function to create a value, all I could do is to append something to PATH, and then remove it again.

**Comment by mrjbq7** [comment]
Well, some kind of test, for some kind of registry value, maybe something thats not important unlike the path?

**Comment by erg** [comment]
The CI is spinning, glorious!

**Comment by AlexIljin** [comment]
Why did the build tests failed? Did I break something?

**Comment by AlexIljin** [comment]
I'm working on a test scenario.

**Comment by AlexIljin** [comment]
I've added a test, and a new word that was necessary (`delete-value`) for the test to run cleanly.

**Comment by mrjbq7** [comment]
@erg you want to look this over and merge and/or comment on this PR?

**Comment by erg** [comment]
It works, squashed/merged. Thanks!

**Comment by erg** [comment]
Oh, and I think the ``leaks`` tests need to be fixed a bit. It seems like we still have random errors.

**Pull request closed without merging**
