### PR TITLE
typo fixed in  CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by shruti-sen2004**
I have corrected a few typos in contributing.md

### CODE REVIEW

**Comment by shruti-sen2004** [comment]
@mrjbq7 Please merge my pull request.

**Comment by razetime** [comment]
there are no useful corrections here.

**Comment by shruti-sen2004** [comment]
okay 👍

**Comment by shruti-sen2004** [comment]
Hello maintainers, I would be grateful if you would remove the hacktoberfest spam label from these pr ....as these contributions were not intended to be under my hacktoberfest contributions...the spam label has affected my contributions that had been made way before...although I have completed my hacktoberfest earlier this month.....hacktober fest has now disqualified me...it is a formal request....let the hacktoberfest invalid tag be there...but please remove the spam tag. I assure you these kind of contributions will not be further continued from my side. 
Thank you.

**Comment by shruti-sen2004** [comment]
@mrjbq7 sorry ..I did not mean to disturb...it's quite important that's why I am tagging you.

**Pull request merged**
