### PR TITLE
checksums.ripemd-docs: fix a typo.

### PR DESCRIPTION
**Pull request by AlexIljin**

### CODE REVIEW

**Comment by mrjbq7** [comment]
Want to ``s/europe/Europe`` also?

**Comment by jonenst** [comment]
Or now that I think of it replace America with USA :)

**Comment by mrjbq7** [comment]
Hah!

**Comment by AlexIljin** [comment]
LOL, I was hoping to make a different commit to fix the Europe.
I'll update the PR.

**Comment by Firsla** [comment]
And openPGP to OpenPGP. :-)

**Comment by AlexIljin** [comment]
Thanks, @Firsla. I've fixed all of the above and updated the PR.

**Comment by mrjbq7** [comment]
Hah, thanks for fixing the nits! Merged!!

**Pull request closed without merging**
