### PR TITLE
Add set methods to ranges

### PR DESCRIPTION
**Pull request by Kacarott**
Adds specific instance methods to various `sets` generics. This is mostly for better performance, but notable is `intersect` which now returns a new intersection range rather than being converted to vectors first. `intersect` was based off the [Julia implementation](https://github.com/JuliaLang/julia/blob/8e14322b5aa344639dd86bf9eabb84afe831fcba/base/range.jl#L1185) of the same.

Code review, improvements, comments, ideas, problems, all welcome :)

### CODE REVIEW

**Comment by mrjbq7** [comment]
Whoops, I merged it too soon.

Had two issues ``USE: nath.functions`` typo.

And can't use ``basis`` library from core.

**Comment by Kacarott** [comment]
Ah how did I miss that. I'll remake the PR once fixed

**Comment by mrjbq7** [comment]
I jumped the gun!

It's all good.

Can ``(intersect)`` be implemented without math.functions? or do we need to have a sets.ranges type vocab that adds this behavior in during bootstrap?

**Comment by Kacarott** [comment]
I am pretty sure the only function it needs from math.functions is `lcm`, but I can just inline that using `gcd` I think.

**Comment by mrjbq7** [comment]
We could also move ``lcm`` to ``core:math``

**Pull request merged**
