### PR TITLE
Block caret code

### PR DESCRIPTION
**Pull request by tgunr**
Introduces 3 kinds of caret shapes: line, box, filled box

(cherry picked from commit 749ecba7c3e80891109273ff714e993afbe003c0)

# Conflicts:
#	basis/ui/gadgets/editors/editors.factor

### CODE REVIEW

**Comment by tgunr** [comment]
Probably needs some tweaking John.

**Comment by tgunr** [comment]
Agreed, was looking for something like ENUM but didn't realize you can use SYMBOL without values. Checking in code shortly.

**Comment by mrjbq7** [comment]
Cool! Thanks!

**Comment by mrjbq7** [comment]
I might make one tweak to the docs and I might rename ``caret-is-shape`` to ``caret-shape``, just a second.

**Comment by tgunr** [comment]
I thought I was having a name conflict so went back to caret-is-shape as the tuple has caret-shape.

**Pull request merged**
