### PR TITLE
Windows Factor's key-down/up event improvements

### PR DESCRIPTION
**Pull request by kusumotonorio**
This change solves some issues with Windows Factor's key-down and key-up events. ( #2119 and #1565 )

1. Ignore caps lock state in key-down/up events
Currently, key-down/up events are affected by the state of caps lock. This behavior is different from Mac Factor.
When you press and release the A key while in the state of caps lock, Mac Factor and Windows Factor each generate an event similar to the following:
Mac Factor:
```
T{ key-down { sym "a" } }
User input: A
T{ key-up { sym "a" } }
```
Windows Factor:
```
T{ key-down { sym "A" } }
User input: A
T{ key-up { sym "A" } }
```
This behavior of the Windows version is not desirable if you want to use the key-down event to execute certain commands by keystrokes. This change ignores the state of caps lock on key-down / up events.

2. Improved key-up events
Windows Factor does not raise key-up events for printable characters other than alphabets and numbers. Also, key-up events are not generated for printable characters on numeric keypads.
The new code solves this problem.

Note
In the past, in Windows Factor, the code that generates the printable character key-down event and the code for character input were closely related. The change has separated them, so we need to test well for character inputs. Also related to this, there are changes in the key-down event that occurs.

For example, when typing ¤ using AltGr on a French keyboard,
```
T{ key-down { mods { C+ A+ } } { sym "¤" } }
```
event was generated, but
```
T{ key-down { mods { C+ A+ } } { sym "$" } }
```
will be. I think this event that generated by the new code is reasonable.

The words called from Windows when the user performs key-down or key-up had become almost the same contents, so they were changed to share the word that takes the word that actually generates the event as an argument.
If you think that this implementation cost is high in terms of execution time, I am ready to rewrite two words with almost the same content.

### CODE REVIEW

**Comment by erg** [comment]
I tested this and it seems really good.

Could you please make this change for handling the errors for ``GetKeyboardState`` and ``ToUnicode``? Unless it's better to ignore the error for some reason.

```
-            keyboard-state GetKeyboardState 0 = not [
-                VK_CONTROL VK_CAPITAL [ 0 swap keyboard-state set-nth ] bi@
-                wParam scan-code keyboard-state chars 2 0 ToUnicode dup 0 = not [
-                    1 <=  [
-                        1 chars nth 8 shift 0 chars nth bitor
-                    ] [
-                        3 chars nth 8 shift 2 chars nth bitor ! dead-key
-                    ] if
-                    1string f hWnd send-key-down/up execute( sym action? hWnd -- )
-                ] [ drop ] if
-            ] when
+            keyboard-state GetKeyboardState win32-error<>0
+            VK_CONTROL VK_CAPITAL [ 0 swap keyboard-state set-nth ] bi@
+            wParam scan-code keyboard-state chars 2 0 ToUnicode dup win32-error=0/f
+            1 <=  [
+                1 chars nth 8 shift 0 chars nth bitor
+            ] [
+                3 chars nth 8 shift 2 chars nth bitor ! dead-key
+            ] if
+            1string f hWnd send-key-down/up execute( sym action? hWnd -- )
```

Finally, we like to keep a flat git history, so could you please rebase your branch onto master and squash it into one patch? I could do it but then the patches come from me..

**Comment by kusumotonorio** [comment]
Thank you for your advice!
I changed their error handling. and rebased. But, unfortunately, I'm not sure if I could get rid of the  patch.

By the way, GetKeyboardState is: 
> If the function succeeds, the return value is nonzero. 
If the function fails, the return value is zero. 

The other hand, win32-error<>0 is:
> : win32-error<>0 ( n -- ) zero? [ win32-error ] unless ;

Changed code is running well, but I'm confused. Am I misunderstanding something?

**Comment by erg** [comment]
Merged, thank you!

**Comment by kusumotonorio** [comment]
I'm glad it was solved.

**Pull request closed without merging**
