### PR TITLE
Feature: ISO 80000 International System of Quantities of binary prefixes

### PR DESCRIPTION
**Pull request by nomennescio**
Although not strictly part of the International System of Units (SI), the addition of binary prefixes to units.si seems the most appropriate choice for vocabulary to me.

### CODE REVIEW

**Comment by mrjbq7** [comment]
Cherry-picked ec7bf34678721c078af6e1b18132a0fc9aeb71ca.

**Comment by mrjbq7** [comment]
Thanks!

**Comment by nomennescio** [comment]
Sorry, I just noticed that other feature accidentally snuck in and was about to check how to delete this pull request (I can't), but you were VERY fast!

**Comment by mrjbq7** [comment]
Wasn't that other feature already pulled a long time ago?

c33a4060661cf4d8a6c94322e445cec09c34503f

**Comment by nomennescio** [comment]
Yes, I made a mistake by creating the feature branch on top of that old feature branch, instead of on master, while working on other edits of `build.sh`.

**Pull request closed without merging**
