### PR TITLE
Change vm comments

### PR DESCRIPTION
**Pull request by AlexIljin**
All comments I could find were changed from /**/ to //, except for a couple embedded in multiline macros.
I've tested the build, and factor.exe/com/dll/lib are built with no errors or warnings. I could not test other OSes.

### CODE REVIEW

**Comment by bjourne** [comment]
Looks pretty nice to me. What do you guys say?

**Comment by bjourne** [comment]
@erg, @mrjbq7? If we want to merge this it is probably better to do it sooner rather than later because it touches so many files.

**Comment by mrjbq7** [comment]
I'm +1, I think @erg liked it and @slavapestov doesn't get a vote right now! :-)

**Comment by bjourne** [comment]
I tried doing the merge with the button :) It didn't turn out right.

**Comment by mrjbq7** [comment]
You can't merge because git.factorcode.org is the true master and we push it to github. So I always have to pull/rebase/merge/push manually.

**Comment by bjourne** [comment]
Ah ok. Doing it that way was a little tricky. Hm..

**Comment by bjourne** [comment]
I pushed it using cherry-pick. Seems to work.

**Pull request merged**
