### PR TITLE
Build infra

### PR DESCRIPTION
**Pull request by nomennescio**
Stores history of runs and benchmarks in DB.
Next step would be adding functionality to view formatted benchmark results in `webapp.mason`.

### CODE REVIEW

**Comment by mrjbq7** [comment]
This might potentially insert multiple runs per gitref, due to rebooting the masons, if that matters, and we should make sure we don't implicitly sort by run-id if we insert the historical benchmarks.

Also, it's de-normalized but the factor db tuple api doesn't quite make normalizing queries properly, so i assume you want to do something like select host/os/cpu on the /speed endpoint (and then optionally maybe a benchmark name in some dropdown), and then render charts.  Or there aren't that many benchmarks, could just render them all after choosing host/os/cpu.

I was thinking maybe the primary key should just be host/os/cpu/gitref instead of a run-id. But maybe that doesn't matter, would be silly to have a flat line in the charts because we kicked the masons a few times while doing whatever with them.

**Comment by mrjbq7** [comment]
I sorta thought storing it as de-normalized rows of host/os/cpu/gitref/benchmark/time would be simpler... but up to you.

**Comment by nomennescio** [comment]
> I sorta thought storing it as de-normalized rows of host/os/cpu/gitref/benchmark/time would be simpler... but up to you.

True, but I was concerned about the size of the DB increasing unnecessarily.

**Comment by nomennescio** [comment]
> This might potentially insert multiple runs per gitref, due to rebooting the masons, if that matters, and we should make sure we don't implicitly sort by run-id if we insert the historical benchmarks.

Multiple runs per gitref are not a problem, just give more accuracy to benchmark data. Furthermore, the data can't discern aspects that impact runtime that aren't caught by a gitref, such as changes to build machines configurations. If that becomes important, additional characteristics can be added to make that distinction.

**Pull request merged**
