### PR TITLE
Distributed messaging Fix

### PR DESCRIPTION
**Pull request by doublec**
This fixes distributed messaging so that it works again. Changes in commit f20ee7a53b264fda515d2a55c8fbea26261de016 broke some use cases - in particular the remote channels functionality.

The test uses a hard coded port. I couldn't work out how to do a randomly generated port that worked with threaded-server.

### CODE REVIEW

**Comment by doublec** [comment]
I've updated [factor-articles.pdf](https://bluishcoder.co.nz/factor-articles.pdf) so that the remote channels example works with these changes if you're looking for usage.

**Comment by mrjbq7** [comment]
I don't understand why this requires a global variable?  Why would that not be up to the user to decided how/where to create and start one and when/how to stop it?

Is the issue with randomized port, trying to know ahead of time by a client what the port is?

**Comment by doublec** [comment]
It is up to the user to decide how/when to create a node. Once it's created distributed messages can be sent between nodes and they access it via the variable.

Currently (pre-this commit) this is done via the threaded-server variable which requires wrapping usage in a with-threaded-server combinator. That combinators starts and stops the server. What is needed though is a persistent server that stays around so other nodes can connect to it. Using a different variable also prevents clashes when using distributed messages from within a threaded server.

The port issue is for the test only. The distributed messaging code lets the user decide the port when calling start-node by having them pass an addrspec.

**Comment by mrjbq7** [comment]
I see, thanks!  Merged!!!

**Pull request closed without merging**
