### PR TITLE
Add rounded corners pen and slider tweaks

### PR DESCRIPTION
**Pull request by inivekin**
Added in the things I didn't get to in the previous pull request https://github.com/factor/factor/pull/3060 making the drawn slider look more like the previous tiled image slider:
- rounded corner pen (based it off the solid pen)
- small grabber on the slider
- added in a fix for https://github.com/factor/factor/issues/3076

### CODE REVIEW

**Comment by mrjbq7** [comment]
Awesome, thanks!

**Comment by mrjbq7** [comment]
Is there an easy way to make it a little narrower (meaning vertical scrollbars are less wide with whitespace on the side and horizontal scrollbars are less tall with whitespace above and below)?  Leaving the arrows the same size they are?

**Comment by mrjbq7** [comment]
(I'm not sure that's a good idea with the spaces but I'm curious)

**Comment by inivekin** [comment]
> Is there an easy way to make it a little narrower (meaning vertical scrollbars are less wide with whitespace on the side and horizontal scrollbars are less tall with whitespace above and below)? Leaving the arrows the same size they are?

The easiest way to do it (assuming just for aesthetic purposes), move the thumb pen to the track and change the width of the filled-border:
```
diff --git a/basis/ui/gadgets/sliders/sliders.factor b/basis/ui/gadgets/sliders/sliders.factor
index b44ce0c0fd..c7f094a1b1 100644
--- a/basis/ui/gadgets/sliders/sliders.factor
+++ b/basis/ui/gadgets/sliders/sliders.factor
@@ -149,8 +149,8 @@ M: slider-pen draw-boundary
     3 [ <gadget> { 1 1 } >>dim content-background <solid> >>interior ] replicate
     [ f track-add <gadget> { 1 1 } >>dim f track-add ] each
     1/2 track-add
-    0 >>fill 1/2 >>align
-    { 1 1 } <filled-border> line-color min-thumb-dim <rounded> >>interior 1/2 track-add ;
+    0 >>fill 1/2 >>align line-color min-thumb-dim <rounded> >>interior 1/2 track-add
+    { 2 0 } <filled-border> ;

 : <thumb> ( orientation -- thumb )
     thumb new-track
```

**Comment by mrjbq7** [comment]
I made a slight tweak I think it looks better in aed0959fce7dda2fcc385a00c68755076fa48d60

**Comment by mrjbq7** [comment]
Thank you, btw!!

**Comment by mrjbq7** [comment]
One other small thing is the "dark circle around the scrollbar arrow" when you click on it is not very circular, should we 

- fix it to be a circle

- change it to a rect

- change it to just make the arrow colored like the button is when clicked?

**Comment by inivekin** [comment]
I think changing it to a rectangle may be the simplest change (and therefore best?):
``` 
diff --git a/basis/ui/gadgets/sliders/sliders.factor b/basis/ui/gadgets/sliders/sliders.factor
index 9181dfa78b..71019fe332 100644
--- a/basis/ui/gadgets/sliders/sliders.factor
+++ b/basis/ui/gadgets/sliders/sliders.factor
@@ -161,7 +161,7 @@ M: slider-pen draw-boundary

 : <slide-button-pen> ( -- pen )
     content-background <solid> dup
-    toolbar-button-pressed-background min-thumb-dim <rounded> dup dup
+    toolbar-button-pressed-background <solid> dup dup
     <button-pen> ;

 : <slide-button> ( orientation amount left right -- button )
```

I think this option tends to some seeming factor convention where base-tones/shapes indicate generic behaviour, (like rounded corners seem to be mean draggable and circles mean multiple selections?)
Is there a convention written down somewhere? The low correlation between tone/hue chosen between theme colours for different elements made selecting the right button colours difficult despite only two main themes - but I'm not familiar with gui programming, if expecting something like that is reasonable. Regardless factor's gui is the first to have me feel that I can leave the terminal and still retain the colours/fonts that I like in a generally legible way, so whatever keeps that vibe has my support!

If it is preferred to keep the circle, I hope the only thing preventing it from looking like a circle is that the arrows aren't properly contained in it? (rounded pen should make a circle when the gadget is square and the `corner-radius`*2 >= dims). Maybe the following to keep the circular shadow:
```
diff --git a/basis/ui/gadgets/sliders/sliders.factor b/basis/ui/gadgets/sliders/sliders.factor
index 9181dfa78b..17be72b744 100644
--- a/basis/ui/gadgets/sliders/sliders.factor
+++ b/basis/ui/gadgets/sliders/sliders.factor
@@ -170,7 +170,7 @@ M: slider-pen draw-boundary
     <repeat-button> { 1 1 } >>min-dim { 1 1 } >>size
     <slide-button-pen> >>interior ;

-CONSTANT: scroll-arrow-dim 10
+CONSTANT: scroll-arrow-dim 6
 CONSTANT: scroll-arrow-dim/2 $[ $ scroll-arrow-dim 2 / ]
 CONSTANT: up-triangle-points { { 0 $ scroll-arrow-dim } { $ scroll-arrow-dim/2 0 } { $ scroll-arrow-dim $ scroll-arrow-dim } }
 CONSTANT: left-triangle-points { { 0 $ scroll-arrow-dim/2 } { $ scroll-arrow-dim  0 } { $ scroll-arrow-dim $ scroll-arrow-dim } }
@@ -178,9 +178,9 @@ CONSTANT: down-triangle-points { { 0 0  } { $ scroll-arrow-dim/2 $ scroll-arrow-
 CONSTANT: right-triangle-points { { 0 $ scroll-arrow-dim } { $ scroll-arrow-dim $ scroll-arrow-dim/2 } { 0 0 } }

 : <up-button> ( orientation -- button )
-    -1 left-triangle-points up-triangle-points [ line-color swap <polygon-gadget> ] bi@ <slide-button> ;
+    -1 left-triangle-points up-triangle-points [ line-color swap <polygon-gadget> { 2 2 } <border> ] bi@ <slide-button> ;
 : <down-button> ( orientation -- button )
-    1 right-triangle-points down-triangle-points [ line-color swap <polygon-gadget> ] bi@ <slide-button> ;
+    1 right-triangle-points down-triangle-points [ line-color swap <polygon-gadget> { 2 2 } <border> ] bi@ <slide-button> ;

 : <slider-pen> ( -- pen )
     content-background <solid> line-color <solid> slider-pen boa ;
 ```

**Comment by mrjbq7** [comment]
The circle looks cool, but the small arrows look less cool.

Trying your rectangle for now which is easy to see.

When we first made the ``ui.theme`` vocabulary, we just made hooks for all the places we used colors, and tried to keep them consistent.  I think another pass is probably needed with reducing it down to some number of high level names like "primary", "secondary", "accent", "background", "active", etc.  We could still keep the current ``toolbar-background`` but have it defer by default to one of the 6 or 8 high level colors.  Make it simpler...

**Comment by mrjbq7** [comment]
Oh! We have a lot more than 2 main themes, for example we have all the base16 themes available:

```factor
IN: scratchpad "solarized" base16-theme-name set-global
IN: scratchpad base16-mode
```

**Comment by inivekin** [comment]
> Another option, is (since I just added all of these: https://tinted-theming.github.io/base16-gallery/) is to switch to base16 as our main theming system...

I happen to be the one who made the initial base16 theme pr, I didn't know more were added! That's a pleasant site for browsing them too, nice to know about.
When I mentioned 2 main themes, I only meant that I was going by an assumption that the light/dark themes were 'official' and the rest are incidental additions and would be allowed to break - perhaps a faulty assumption.

As an aside, I'm also a bigger fan of base2-tone themes https://base2t.one/demo/space/ as really 4 colours is all you (technically) need, but base16 is far more widely used and would require less careful handling for sure.
If others in the factor community don't think the base16 themes too radical a limit for base apps and if you're looking for someone to do some basic tasks for a base16 refurbishment I would be into trying to help!

**Pull request merged**
